/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene.ls
 */
export class RuntimeScriptBase extends Laya.Scene {
    public Animation!: Laya.Animation;
    public Prefab2D!: Laya.Box;
    public Panel!: Laya.Panel;
    public Skeleton!: Laya.Skeleton;
    public Rigid1!: Laya.Text;
    public Rigid2!: Laya.Text;
}

